### PR TITLE
Fix focus and blur event handlers in bubbling phase

### LINKED ISSUE #21: Non-bubbling, composed events fire on the wrong nodes
Non-bubbling, composed events such as `focus` and `blur` will be fired on all nodes in the composed path. Instead, they should only be fired on the shadow hosts in the composed path.

### PR DESCRIPTION
**Pull request by azakus**
Only fire 'bubbling' phase focus/blur events on shadowroot hosts and initial target

Fixes #21

### CODE REVIEW

File: src/event-mixin.js [hunk 1]
```diff
@@ -204,6 +205,10 @@ function retargetNonBubblingEvent(e) {
   Object.defineProperty(e, 'eventPhase', {value: Event.BUBBLING_PHASE});
   for (let i = 0; i < path.length; i++) {
     node = path[i];
+    // bubbling phase should only fire on original target and all shadowroot hosts
+    if (i !== 0 || !node.shadowRoot) {
```
Comment (cdata) [inline src/event-mixin.js]: Is there a `shadowRoot` property under ShadyDOM? How is `node.root` different?

Comment (azakus) [inline src/event-mixin.js]: Yes, Polymer is what adds the `.root` property

**Comment by sorvell** [comment]
Needs test.

**Comment by azakus** [comment]
Tests have been added @sorvell

**Comment by azakus** [comment]
@sorvell updated

File: src/event-mixin.js [hunk 2]
```diff
@@ -196,14 +196,32 @@ function retargetNonBubblingEvent(e) {
...
+
+  // set the event phase to `AT_TARGET` as in spec
+  Object.defineProperty(e, 'eventPhase', {value: Event.AT_TARGET});
+
+  // if the event bubbles through a `slot` node, then the next shadowroot host should be skipped,
+  // as the event target is in the light dom of the shadowroot host, and should not retarget
+  let throughSlot = false;
   for (let i = 0; i < path.length; i++) {
     node = path[i];
+    if (node.localName === 'slot') {
```
Comment (sorvell) [inline src/event-mixin.js]: I think rather than depending on traversing through `slot` here, it would be more explicit to (1) keep track of the root on which the last event was generated, (2) only generate an event if you encounter a node that has a shadowRoot that is that tracked root.
