### PR TITLE
Workaround Firefox + Selenium error

### LINKED ISSUE #145: Firefox Selenium driver fails to execute Javascript after webcomponents-lite.js is loaded
The simple test
```
    @Test
    public void printFoo() {
        WebDriver driver = new FirefoxDriver();
        try {
            driver.get("http://localhost:5000/");
            System.out.println(((JavascriptExecutor) driver)
                    .executeScript("return 'foo';"));
        } finally {
            driver.quit();
        }
    }
```
With an index.html containing
```
<!doctype html>
<html>
  <head>
    <script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
  </head>
  <body>
    Hello
  </body>
</html>
```
Fails with the error
```
org.openqa.selenium.WebDriverException: Error: Permission denied to access property "__eventWrappers"
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'g-10-64-12-108.guest.vaadin.com', ip: '10.64.12.108', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/var/folders/51/thqqj09d3wlgdcx7hpb9hyfc0000gn/T/rust_mozprofile.xzSmI7PtLooq, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=54.0, platformVersion=16.5.0, moz:processID=32569.0, browserName=firefox, javascriptEnabled=true, platformName=darwin}]
Session ID: 444f51d0-cf86-6043-990b-e2d15bda49fc
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:573)
```

The problem originates in https://github.com/webcomponents/shadydom/blob/master/src/patch-events.js#L398

Changing 
```
if (fnOrObj.__eventWrappers) {
```
 to
```
  try {
    wrapper = fnOrObj.__eventWrappers);
  } catch (e) {
    wrapper = null;
  }
  if (wrapper) {
```
makes the test pass.

### PR DESCRIPTION
**Pull request by azakus**
Try/catch accessing wrappers in removeEventListener to work around https://bugzilla.mozilla.org/show_bug.cgi?id=1353074

Fixes #145

### CODE REVIEW

File: src/patch-events.js [hunk 1]
```diff
@@ -395,12 +409,13 @@ export function removeEventListener(type, fnOrObj, optionsOrCapture) {
   let target = (optionsOrCapture && optionsOrCapture.__shadyTarget) || this;
   // Search the wrapped function.
   let wrapperFn = undefined;
-  if (fnOrObj.__eventWrappers) {
-    let idx = findListener(fnOrObj.__eventWrappers, target, type, capture, once, passive);
+  let wrappers = getEventWrappers(fnOrObj);
```
Comment (sorvell) [inline src/patch-events.js]: remove the previous line?
