### PR TITLE
Fix input caret in firefox

### LINKED ISSUE #61: In Firefox when ShadyDOM is loaded carets disappear from <input>
When ShadyDOM is loaded in Firefox (50.0.2) all `<input>` elements loose their caret when focused.

screen shot 2016-12-05 at 11 28 42 am

You can reproduce with the following HTML or in http://jsbin.com/rifakizoju/edit?html,output

```html
<!DOCTYPE html>
<html>
<head>
  <title>JS Bin</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <script src="https://cdn.rawgit.com/webcomponents/shadydom/master/shadydom.min.js"></script>
  <style>
    input {
      display: block;
      font-size: 1rem;
    }
  </style>
</head>
<body>
  <label>
    Will not show caret when input it focused&hellip;
    <input type="text">
  </label>
</body>
</html>
```

All other functionality of the`<input>` remains appears to be fine.

### PR DESCRIPTION
**Pull request by azakus**
Fixes #61

### CODE REVIEW

File: src/patch-events.js [hunk 1]
```diff
@@ -266,11 +281,7 @@ export function addEventListener(type, fn, optionsOrCapture) {
   if (fn.__eventWrappers) {
     // Stop if the wrapper function has already been created.
     for (let i = 0; i < fn.__eventWrappers.length; i++) {
-      if (fn.__eventWrappers[i].node === this &&
```
Comment (valdrinkoshi) [inline src/patch-events.js]: I remember doing this instead of a function because of better performance. Is having `listenerSettingsEqual` function strictly needed?

**Comment by azakus** [comment]
We already have tests for focus and blur events, but testing that the caret is rendered in firefox is not something I think we can do. There is a smoke test available though.

File: src/patch-events.js (hunk 1 above)
Comment (azakus) [inline src/patch-events.js]: I guess not, but that code looked real ugly. Is the performance difference actually measurable?

Comment (valdrinkoshi) [inline src/patch-events.js]: I must find the PR where I measured this. It was showing that, because this is a high frequency path, invoking functions had a cost

Comment (valdrinkoshi) [inline src/patch-events.js]: This is the PR,with test case https://github.com/webcomponents/shadydom/pull/35#issuecomment-258045254

**Comment by valdrinkoshi** [comment]
LGTM, up to you about that perf thing with the function.

**Comment by valdrinkoshi** [comment]
@azakus I tested master vs this PR and it doesn't seem to really affect too much perf http://jsbin.com/muduxij/2/edit

:shipit:
