### PR TITLE
Fix timing issue if modifying slot name before rendering

### LINKED ISSUE #264: Change a slot name during an async rendering can throw
#### Steps to Reproduce
```js
const host = document.createElement('div');
document.body.appendChild(host);
host.attachShadow({mode: 'open'});
const slot = document.createElement('slot');
host.shadowRoot.appendChild(slot);
slot.setAttribute('name', 'foo');
```
If a shadyroot is inside of a pending async render, the slotMap may not have the slot assigned to it yet and will throw trying to redistribute.

#### Expected Results
Slot's name is `foo`

#### Actual Results
Throws `TypeError: Cannot read property \'indexOf\' of undefined`

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### PR DESCRIPTION
**Pull request by azakus**
slotMap has not been set up yet, so name changes will hit an `undefined`
trying to affect a slot name change

Fixes #264

### CODE REVIEW

File: src/attach-shadow.js [hunk 1]
```diff
@@ -482,7 +482,7 @@ class ShadyRoot {
   }
 
   _updateSlotName(slot) {
-    if (!this._slotList) {
+    if (!this._slotList || this._pendingSlots && this._pendingSlots.length) {
```
Comment (sorvell) [inline src/attach-shadow.js]: Let's call `_validateSlots` since it's more explicit.

File: tests/slot-scenarios.html [hunk 2]
```diff
@@ -188,7 +188,17 @@
             window.ShadyDOM.flush();
           }
         });
-      })
+      });
+
+      test('slots can be modified before rendering', function() {
```
Comment (sorvell) [inline tests/slot-scenarios.html]: Let's go ahead and test if a node gets distributed to the right spot in this case.

Comment (azakus) [reply tests/slot-scenarios.html]: Done
